package io.github.dim971.textmorph.core

import com.google.gson.Gson
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import java.io.InputStreamReader

/**
 * Reading the checked-in fixtures.
 *
 * Every fixture file is generated by a script under `Tools/` and is byte
 * identical to the iOS twin's copy, which is what makes a parity claim checkable
 * rather than asserted. CI on both sides compares the digests.
 */
internal object Fixtures {
    private val gson = Gson()

    fun json(name: String): JsonObject {
        val stream =
            requireNotNull(javaClass.getResourceAsStream("/$name.json")) {
                "fixture $name.json is missing from the test resources"
            }
        return InputStreamReader(stream, Charsets.UTF_8).use {
            gson.fromJson(it, JsonObject::class.java)
        }
    }

    /**
     * A double, or one of the two values JSON cannot carry.
     *
     * `JSON.stringify` turns NaN into null and minus zero into zero, and both of
     * those are exactly what the broken spring case produces, so the generator
     * writes them as strings and this reads them back.
     */
    fun exactDouble(element: JsonElement): Double {
        if (element.asJsonPrimitive.isString) {
            return when (val raw = element.asString) {
                "NaN" -> Double.NaN
                "-0" -> -0.0
                else -> error("unexpected exact double $raw")
            }
        }
        return element.asDouble
    }

    /** A nullable integer, for an alignment entry that means "arrived". */
    fun nullableInt(element: JsonElement): Int? = if (element.isJsonNull) null else element.asInt
}

/**
 * Escapes the characters that make a failure message unreadable in a terminal,
 * which in this corpus is most of the interesting ones.
 */
internal fun escaped(value: String): String {
    val body =
        value
            .map { character ->
                if (character.code in 0x20..0x7E) {
                    character.toString()
                } else {
                    "\\u{%04X}".format(character.code)
                }
            }.joinToString("")
    return "\"$body\""
}

/** A failure list, trimmed to something a reader can act on. */
internal fun report(
    failures: List<String>,
    total: Int? = null,
): String {
    val header =
        if (total != null) {
            "${failures.size} of $total disagree:"
        } else {
            "${failures.size} disagree:"
        }
    return (listOf(header) + failures.take(12)).joinToString("\n")
}
